services:

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      #- mongo-data:/data/db
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - node-network

  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - backend-data:/uploads
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/base
      - PORT=5000
    networks:
      - node-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000
      #- REACT_APP_API_URL=http://localhost:5000

volumes:
  mongo-data:
  backend-data:

networks:
  node-network:
    driver: bridge
